
objs-y += assign.o
objs-y += binary_op.o
objs-y += block.o
objs-y += cast.o
objs-y += expression_stmt.o
objs-y += func_call.o
objs-y += function.o
objs-y += if.o
objs-y += literal_number.o
objs-y += literal_string.o
objs-y += return.o
objs-y += unary_op.o
objs-y += var_load.o
objs-y += var_store.o
objs-y += while.o
objs-y += var.o

